Arenas:
  Bending:
    WorldName: RisePVP
    ActiveRegion:  B_Arena
    TriggerRegion: B_Arena_2
    Schematic: plugins/WorldEdit/schematics/b_arena_area.schematic
  PrisonMine:
    WorldName: Prison
    ActiveRegion: Prison_Mine
    TriggerRegions: Prison_Mine_Zone
    Schematic:plugins/WorldEdit/schematics/prison_mine.schematic
  PrisonWood:
    WorldName: Prison
    ActiveRegion: Prison_Wood
    TriggerRegions: Prison_Mine_Zone
    Schematic: plugins/WorldEdit/schematics/prison_wood.schematic
  