name: dTools
main: main.dTools
softdepend: [WorldGuard, WorldEdit]
version: 1.1.4
commands:
  broadcastcommand:
    description: Broadcasts a message to all other users.
    aliases: [bc, broadcast]
    usage: /<command>
    default: op
  joindate:
    description: Look up the date when a user first joined MegaCraft.
    usage: /<command>
    permission: dTools.joindate
    default: op
  dtools:
    description: Custom dTools Commands.
    aliases: [dtools]
    usage: /<command>
    permission: dTools.admin
    defualt: op
  donationreward:
    description: Award a random item to every online player.
    aliases: [dreward, donationreward]
    usage: /<command>
    permission: dTools.lottery
    default: op
  commandpetcannon:
    description: Launch your pet at your foes!
    aliases: [pc, petcannon, commandpetcannon]
    useage: /<command>
    permission: dTools.petcannon
    default: op
  effectscommand:
    description: Custom Effects
    aliases: [eff, effects, effectscommand]
    useage: /<command>
    permission: dTools.effectscommand
    default: op
  blockcommand:
    description: Auto-Crafts Ignots into Blocks
    aliases: [block, blockcommand]
    useage: /<command>
    permission: dTools.blockcommand
    default: op
  listcommand:
    description: Better /who command 
    aliases: [list, who, listcommand]
    usage: /<command>
    permission: dTools.listcommand
    default: true 
permissions:
  dTools.*:
    description: gives all permissions of the plugin commands
    default: op
    children:
      dTools.effectscommand:
        default: op
      dTools.commandpetcannon:
        default: op
      dTools.broadcastcommand:
        default: op
      dTools.listcommand:
        default: true
      dTools.respawnarea:
        default: op
      dTools.blockcommand:
        default: op
      dTools.donationreward:
        default: op